# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileNocTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileNocTask
  pod 'Alamofire', '~> 4.7'
  pod 'PromisesSwift', '~> 1.2.3'

  target 'MobileNocTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileNocTaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
